[workspace]
authors = ["Arlyn <109974543+ArsLinear@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "fdm-cvsim"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.7,<3.15"
